sensor_kit_base_link:
  lidar_os1/base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_os2/base_link:
    x: 0.0
    y: 0.0
    z: -0.2
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_front/camera_link:
    x: 0.75
    y: 0.0
    z: -0.32
    roll: -0.000
    pitch: 0.01
    yaw: -0.00
  camera_rear/camera_link:
    x: -0.8
    y: 0.0
    z: -0.32
    roll: 3.14152
    pitch: 0.275
    yaw: 3.05
  camera_front_left/camera_link:
    x: 0.39
    y: 0.4
    z: -0.25
    roll: 0.0
    pitch: 0.0
    yaw: 0.7854
  camera_front_right/camera_link:
    x: 0.39
    y: -0.4
    z: -0.25
    roll: 3.141592
    pitch: 0.0
    yaw: -0.7854
  camera_rear_left/camera_link:
    x: 0.2
    y: 0.4
    z: -0.25
    roll: 0.0
    pitch: 0.0
    yaw: 2.3562
  camera_rear_right/camera_link:
    x: 0.2
    y: -0.4
    z: -0.25
    roll: 3.141592
    pitch: 0.0
    yaw: -2.356
  # traffic_light_right_camera/camera_link:
  #   x: 0.05
  #   y: -0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  # traffic_light_left_camera/camera_link:
  #   x: 0.05
  #   y: 0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  adma/gnss_link:
    x: -0.45
    y: 0.0
    z: -0.24
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

adma/gnss_link:
  adma/imu_link:
    x: -0.87
    y: 0.015
    z: -1.26
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

front_axle_center_link:
  radar_front_left/base_link:
    x: 0.66
    y: 0.72
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: 0.7854
  radar_front_right/base_link:
    x: 0.66
    y: -0.72
    z: 0.18
    roll: 0.0
    pitch: 0.0
    yaw: -0.7854
  radar_rear_left/base_link:
    x: -3.24
    y: 0.8
    z: 0.13
    roll: 0.0
    pitch: 0.0
    yaw: 2.3562
  radar_rear_right/base_link:
    x: -3.24
    y: -0.8
    z: 0.13
    roll: 0.0
    pitch: 0.0
    yaw: -2.3562