base_link:
  sensor_kit_base_link:
    x: 1.0
    y: 0.0
    z: 1.915
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  front_axle_center_link:
    x: 2.7
    y: 0.0
    z: 0.29
    roll: 0.0
    pitch: 0.0
    yaw: 0.0