sensor_kit_base_link:
  lidar_os1/base_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  lidar_os2/base_link:
    x: 0.0
    y: 0.0
    z: -0.135
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_front/camera_link:
    x: 0.59
    y: 0.0
    z: -0.275
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  camera_rear/camera_link:
    x: -0.75
    y: 0.0
    z: -0.275
    roll: 3.141592
    pitch: 0.0
    yaw: 3.141592
  camera_front_left/camera_link:
    x: 0.39
    y: 0.4
    z: -0.25
    roll: 0.0
    pitch: 0.0
    yaw: 0.7854
  camera_front_right/camera_link:
    x: 0.39
    y: -0.4
    z: -0.25
    roll: 3.141592
    pitch: 0.0
    yaw: -0.7854
  camera_rear_left/camera_link:
    x: 0.2
    y: 0.4
    z: -0.25
    roll: 0.0
    pitch: 0.0
    yaw: 2.3562
  camera_rear_right/camera_link:
    x: 0.2
    y: -0.4
    z: -0.25
    roll: 3.141592
    pitch: 0.0
    yaw: -2.356
  # traffic_light_right_camera/camera_link:
  #   x: 0.05
  #   y: -0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  # traffic_light_left_camera/camera_link:
  #   x: 0.05
  #   y: 0.0175
  #   z: -0.1
  #   roll: 0.0
  #   pitch: 0.0
  #   yaw: 0.0
  radar_rear_left:
    x: -0.5
    y: 0.75
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 2.3562
  radar_rear_right:
    x: -0.5
    y: -0.75
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: -2.3562
  radar_front_left:
    x: 3.3
    y: 0.75
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: 0.7854
  radar_front_right:
    x: 3.3
    y: -0.75
    z: 0.5
    roll: 0.0
    pitch: 0.0
    yaw: -0.7854
  adma/gnss_link:
    x: -0.45
    y: 0.0
    z: -0.24
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

adma/gnss_link:
  adma/imu_link:
    x: -0.87
    y: 0.0
    z: -1.26
    roll: 0.0
    pitch: 0.0
    yaw: 0.0